# DataNest Home Lab - Local Split-Horizon DNS Targeted Routes
# Place in /etc/dnsmasq.d/04-datanest-homelab.conf on Pi-hole v6 (LXC 100)
# Enable parsing with: pihole-FTL --config misc.etc_dnsmasq_d true

address=/vault.datanest.my.id/192.168.1.107
address=/portainer.datanest.my.id/192.168.1.107
address=/media.datanest.my.id/192.168.1.107
address=/pdf.datanest.my.id/192.168.1.107
address=/photos.datanest.my.id/192.168.1.107
address=/drive.datanest.my.id/192.168.1.107
address=/proxmox.datanest.my.id/192.168.1.105
